notifiers:

  pushover:
    enabled: false
    send_lowest_priority_on_disabled: false
    user: 
    token: 

  telegram:
    enabled: false
    chat_id:
    token:

  twilio:
    enabled: false
    accountSid: 
    notif_number: 
    authToken: 
    senderNumber: 

  discord:
    enabled: false
    username: 
    avatar_url: 
    webhook_url: 
    
  email:
    enabled: 
    port: 
    host: 
    auth_user: 
    auth_pass: 
    dest_email: 
    
ignore:

token:
